sudo: required
language: bash
services:
- docker
before_install:
- docker build -t jinwuzhao/emacs-godev .
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
env:
  global:
  - secure: Iufc2YbcZGAI6mTT0kOtITQVKsKleR5pMivcGhhpxuDKf527e6iOVMUONvV+hXYTylek4eRtjjBbZNKPeWXU9j8PqwkA5S12jE4rwf0gxzj3Ew3vAcPgGrDJm+uFstOYr64oLo9WaGMDmsclubCuDfXpb8BQ3sHV/PK3HmE+tR6rgARcUMmyQLp6q8IYCP62sbF7cWVTxxcmkuPJ3jQNvsHKCMtGtzYn8WL0paGqXoRYMY09+cqBUkhA6M7vKOg7wigX5sDbsHRPJcTzBxPDpCLw3go7e9TSnXufr1F7JnMdYAll1HA69mnYJO9k2tAC/iN+1PkjXXhI4lfm3hmI+Lu2xsnrwSGd8UmorVaCX2f/7NR8iL835IoVEsiPzwX1ryItaNuyQ55cendiNwflu70KPGBERVOpJ7cwIapTVz2bn6KkBijc8SOGND6jf2x1Cub+H8ipvL0dsFPYuFn+hUklJQ8jUy9Kaq2XrSZRJ7pt2RiUlvJTaqGmMEqfwSYdjyEXYiqfB0qA8Hkz6kdJVSzR16vGPjkbhSVuhgCCsGCd9p/iieBCrvJ15dDQb5RrDzIWFNfCE8S+wG7KyBe761iyo3W7O0xRR0Cx4e9doVVgD5xI9NbHrnQtQDlsfEaOYTz5wf9SKs9h1gd7fY194EEZ858qi1DCbhUjfrPXlyA=
  - secure: SvbbtPrWKYbw4WAyCAJjQ4VGfQKJhfsb/PjKehf3+jtwrsaQ67lD5BsbBH7eJbLBKR3UmVof8DLXHxw4BSc9srmgGkL+h4oVbWPs0EsmBWTBrdolwJVV7wlU9P+pv69RBDTMjOWgPG8/K5c1ZAxlmcT3ECTdHWsoADoftb2lpzMB8kBBuCpEMzP6LYYH2DG6MS1n6AyruY1WsHYq7XArXRTWZOQMq3iObkQdqzsRqvMOnnCG5JacSJdB0RrbPxN1cMzvh1uL+yAzTuMhKWjBQ3/96iBlxCETR0AtBvihcbzZkB8zGJPtrUwY+PAH2LJmpLMT7nIeU+mP0XmBS9UQLhHSLB34yupA9YqvxwahMV6VBe6MgNyH8UFPCxJHf4rjjedFJyLIfG9/DgcT4KdqNW44RcC0SnKMwwTAx78LxkIIZpVCMJZBa3FpYGb8h0e0eKg40SfwoUE/bg3Xq9h0h8r1K5M2K72GEY+McTxv8ErRpDI1l7hSY2Z96fjoNctXfWUL/2qTRgENUZf/HSXovxGMl2xm0L/q4LImQYPbaJipUHMV9dwOWObShoSY3Eo8s64Y+190cHMqTgFarqJ65pS8bNz/KIz2J0w94w1Yp/ZGvPnUg+HxqqlgEu1Hk6KyihtdtGGT7djQtDqwcDDkIxBIQQh3b8ZsJfDRSuPT51g=
