#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push jinwuzhao/emacs-godev
docker tag jinwuzhao/emacs-godev jinwuzhao/emacs-rust:$TRAVIS_TAG
docker push jinwuzhao/emacs-godev:$TRAVIS_TAG
docker logout
